# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        azurerm = {
          source  = "hashicorp/azurerm"
          version = "4.4.0"

        }
      }
    }

    provider "azurerm" {
        features {}
        subscription_id = "0ebd9941-c5ec-494d-92d5-f02a879aa29a"
        tenant_id = "76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61"
    }
